# -*- coding: utf-8 -*-
"""website_analyse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnenjGBqjJcPWKpNDwvzlfVzrVocRXbJ
"""

import numpy as np
import pandas as pd

def website_analyse():
  df = pd.read_csv('website_visits_december_2024.csv')

  pages = df['Просмотренные страницы']
  mean_pages = round(np.mean(pages),2)
  print(f'1) Среднее количество просмотренных страниц:{mean_pages}')

  time = df['Время на сайте (сек)']
  time_std = round(np.std(time),2)
  print(f'2) Стандартное отклонение:{time_std}')

  time_mean = np.mean(time)
  time_CV = (time_std/time_mean)*100
  if time_CV >= 0.25:
    print('3) Высокая/Умеренная/Слабая вариабельность:Высокая вариабельность')
  elif time_CV <= 0.1:
    print('3) Высокая/Умеренная/Слабая вариабельность:Слабая вариабельность')
  else:
    print('3) Высокая/Умеренная/Слабая вариабельность:Умеренная вариабельность')

  mobile = df[df['Тип устройства'] == 'Мобильное']
  pages_mobile = mobile['Просмотренные страницы']

  desktop = df[df['Тип устройства'] == 'Десктоп']
  pages_desktop = desktop['Просмотренные страницы']

  from scipy.stats import ttest_ind
  stat, p_value = ttest_ind(pages_mobile, pages_desktop)
  if p_value < 0.05:
    print('4) Есть статистически значимая разница в количестве страниц/Нет статистически значимой разницы:Есть статистически значимая разница в количестве страниц')
  else:
    print('4) Есть статистически значимая разница в количестве страниц/Нет статистически значимой разницы: Нет статистически значимой разницы')

  print(f'p_value = {p_value}')

website_analyse()